ALTER TABLE "Comment" ENABLE ELECTRIC;

ALTER TABLE "Conversation" ENABLE ELECTRIC;

ALTER TABLE "Customer" ENABLE ELECTRIC;

ALTER TABLE "Design" ENABLE ELECTRIC;

ALTER TABLE "IdCounter" ENABLE ELECTRIC;

ALTER TABLE "Label" ENABLE ELECTRIC;

ALTER TABLE "Message" ENABLE ELECTRIC;

ALTER TABLE "Milestone" ENABLE ELECTRIC;

ALTER TABLE "Project" ENABLE ELECTRIC;

ALTER TABLE "Sprint" ENABLE ELECTRIC;

ALTER TABLE "Status" ENABLE ELECTRIC;

ALTER TABLE "Subtask" ENABLE ELECTRIC;

ALTER TABLE "Task" ENABLE ELECTRIC;

ALTER TABLE "Team" ENABLE ELECTRIC;

ALTER TABLE "UserAction" ENABLE ELECTRIC;

ALTER TABLE "View" ENABLE ELECTRIC;

ALTER TABLE "Workspace" ENABLE ELECTRIC;

ALTER TABLE "LabelsOnConversations" ENABLE ELECTRIC;

ALTER TABLE "ConversationsOnTasks" ENABLE ELECTRIC;

ALTER TABLE "LabelsOnTasks" ENABLE ELECTRIC;

ALTER TABLE "LabelsOnProjects" ENABLE ELECTRIC;